Add check if streamer is offline

diff --git a/.github/workflows/tes_tiktok.yml b/.github/workflows/tes_tiktok.yml
--- a/.github/workflows/tes_tiktok.yml
+++ b/.github/workflows/tes_tiktok.yml
@@ -1,4 +1,4 @@
-name: Rekam Cloud TikTok (Ukuran Kecil Original Resolution)
+name: Rekam Cloud TikTok
 
 on:
   workflow_dispatch:
@@ -23,27 +23,30 @@ jobs:
           echo "${{ secrets.RCLONE_CONFIG_DATA }}" | base64 -d > ~/.config/rclone/rclone.conf
 
       - name: Rekam Live TikTok (Streamlink 1 Menit)
-        continue-on-error: true
         run: |
           timeout 60s streamlink --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
                  "https://www.tiktok.com/@argus.bkent/live" best \
-                 -o "raw_video.flv" --force || true
+                 -o "raw_video.flv" || true
 
       - name: Kompres Ukuran & Convert ke MP4 Playable GDrive
         run: |
-          if [ -f "raw_video.flv" ] && [ -s "raw_video.flv" ]; then
+          if [ -s "raw_video.flv" ]; then
             ffmpeg -y -i raw_video.flv \
                    -c:v libx264 -crf 28 -preset superfast -pix_fmt yuv420p \
                    -c:a aac -b:a 96k \
                    -movflags +faststart \
-                   rekaman_argus.mp4 || true
+                   rekaman_argus.mp4
             rm -f raw_video.flv
+          else
+            echo "STREAMER OFFLINE / FILE FLV KOSONG"
           fi
 
       - name: Cek & Upload ke GDrive
-        if: always()
         run: |
           ls -la
           if [ -f "rekaman_argus.mp4" ]; then
             rclone copy rekaman_argus.mp4 gdrive:TikTok_Replays --progress
+          else
+            echo "ERROR: File rekaman_argus.mp4 tidak ada. Kemungkinan streamer offline!"
+            exit 1
           fi
